version: '3.7'
services:
  webapp:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: humanlib-server:lates
    container_name: humanlib-server
    ports:
      - '8080:8080'
  db:
    image: postgres:11.2-alpine
    container_name: humanlib-db
    environment:
      POSTGRES_USER: 'humanlib'
      POSTGRES_PASSWORD: 'lib123'
      POSTGRES_DB: 'humanlib'
    expose:
      - "5432"
    restart: always